# Generated by Django 5.2.4 on 2025-07-15 07:16

import django.contrib.gis.db.models.fields
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('areas_of_interest', models.TextField(blank=True)),
                ('user_documents', models.FileField(upload_to='documents')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location_of_home_address', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('location_of_office_address', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('image', models.ImageField(upload_to='my_images/')),
            ],
        ),
    ]
